### PR TITLE
Documentation links changed due to site migration

### LINKED ISSUE #13: Docs, coverage, and doxygen links no longer work.
Recent changes to mooseframework.org have caused the links in the README to no longer work.

### PR DESCRIPTION
**Pull request by brianmoose**
closes #13

### CODE REVIEW

**Comment by bwspenc** [comment]
@brianmoose I'm good with the changes, but the test is failing, I assume because of the documentation build failure and the sync at the end. Do we merge this anyway because the documentation system is in the middle of being changed, or disable those checks temporarily?  I'm good with however you want to handle this. Also, I just created issue #12 for this work. Please reference that in your PR.

**Comment by bwspenc** [comment]
Please ref issue #12 in your commit, and then I'll merge it when the tests pass.

**Comment by brianmoose** [comment]
I disabled checking/building of the documentation until it is migrated. It would always fail and wouldn't even generate anything useful.
These documentation links changes are not really related to the moose documentation change.
This was due to the mooseframework.org server change and some resulting changes in the directory layout when we moved things to a new server.

**Comment by bwspenc** [comment]
OK, just make an issue appropriate for this and reference it.

**Comment by brianmoose** [comment]
closes #13

**Pull request merged**
