### PR TITLE
Updated NEML and fixed tests

### LINKED ISSUE #76: Update NEML and fix NEML tests
The submodule version of NEML is pretty old and the test material XML files for the benchmark tests are pretty wonky, which breaks the power law creep test.  Update NEML and fix the tests.

### PR DESCRIPTION
**Pull request by reverendbedford**
- Updated NEML submodule to current dev
- Fixed NEML XML material definitions in the benchmark tests
- Updated NEML power law benchmark to run to full time

closes #76

### CODE REVIEW

**Comment by reverendbedford** [comment]
Can someone help me with the test failure?  I can't parse the info provided by civet to figure out what's going wrong...

**Comment by bwspenc** [comment]
Thanks for submitting this!  I was meaning to do just this, but you beat me to it.

**Comment by bwspenc** [comment]
@milljm The test failure here looks like a problem with the testing system, rather than with any of the tests.  Any idea what's going on?

**Comment by milljm** [comment]
Civet recently had a bad gateway error code (probably due to the server being over burdened at the moment). You can try invalidating the target, see if it that works.

**Comment by reverendbedford** [comment]
Actually no this is my fault.  Something deep in NEML is failing one of the runtime checks that you guys have setup on dbg builds.  But the odd part is that its causing tests to fail that have nothing to do with NEML...  Let me see if I can figure it out.

**Comment by reverendbedford** [comment]
Well it's some static data I have in the new version of NEML (specifically the crystal symmetry operators in the crystal plasticity module).  I don't think my code is actually wrong, but let me see if I can fix this...

**Comment by bwspenc** [comment]
It might make sense to deal with the updates to the tests in a separate PR from the update to the NEML version. Your call -- whatever is easier for you.

**Comment by reverendbedford** [comment]
That probably would have been a better way to do it in retrospect.  But anyway I patched NEML and this passes everything.

**Comment by bwspenc** [comment]
Great, thanks for sorting that out!

**Pull request merged**
