### PR TITLE
Patch non-defaulted nonlinear system arguments

### PR DESCRIPTION
**Pull request by lindsayad**
And also put `operator <<` in the `neml2` namespace

### CODE REVIEW

**Review by hugary1995 — APPROVED** [review]
Thanks.

**Review by hugary1995 — APPROVED** [review]

**Comment by hugary1995** [comment]
The "Test without libtorch" failure is not your fault and is expected. I will fix that tomorrow.

**Comment by lindsayad** [comment]
@loganharbour you mentioned that you've been doing stuff with blackbear docs recipes related to libtorch? So does that mean we should not attempt to build docs on the "without libtorch" recipe?

**Comment by loganharbour** [comment]
> @loganharbour you mentioned that you've been doing stuff with blackbear docs recipes related to libtorch? So does that mean we should not attempt to build docs on the "without libtorch" recipe?

No, we definitely should. This breakage caught us in an attempt to make blackbear right. I made a bunch of recipe changes with the intention of them breaking blackbear for now, but for @hugary1995 to fix up soon.

However, looks like this one in particular we need to disable briefly while we get your change through. I'll do that shortly and merge.

**Review by loganharbour — APPROVED** [review]

**Comment by loganharbour** [comment]
Merging despite failure. Documentation w/o torch is now allowed to fail and will be resolved by @hugary1995 in the future.

Odds are we'll remove it anyway and not allow neml2 without torch.

**Pull request merged**
