### PR TITLE
Loosen up test floor tolerances 

### PR DESCRIPTION
**Pull request by recuero**
Some of the tests tend to diff when run on different platforms (e.g. MacOS). This PR reduces the floor of such tests so that, in combination with the relative tolerance, the precision demanded of the result is looser. This makes that some of the tests may not check for stresses values which are on the order of e-6.

Refs. #139

### CODE REVIEW

**Comment by recuero** [comment]
@bwspenc I think I don't have the rights to trigger the testing system.

**Comment by SudiptaBiswas** [comment]
I already have a PR on this here #140.

**Comment by recuero** [comment]
Yeah, that PR should go in first and then see if there's anything else diffing.

**Comment by SudiptaBiswas** [comment]
After #140 was merged, all the tests are passing for me. @recuero Do you still see tests failing?

**Comment by recuero** [comment]
@SudiptaBiswas Now things look okay locally.

**Pull request closed without merging**
