### PR TITLE
Get rid of deprecated usage of declarePropertyOld

### LINKED ISSUE #19: Get rid of deprecated usage of declarePropertyOld()
It has been replaced by getMaterialPropertyOld()

### PR DESCRIPTION
**Pull request by bwspenc**
closes #19

### CODE REVIEW

**Comment by bwspenc** [comment]
@rwcarlsen If you're around, could you take a look at this?

**Comment by bwspenc** [comment]
@rwcarlsen Could you please merge this if you're good with it?

**Comment by rwcarlsen** [comment]
I don't have merge rights.

**Comment by bwspenc** [comment]
Now you do.

**Comment by bwspenc** [comment]
Thanks!

**Pull request merged**
