### PR TITLE
Updated neml to current dev

### LINKED ISSUE #83: Update blackbear to the newest NEML dev
You need the new material models implemented in NEML since the last update.

### PR DESCRIPTION
**Pull request by reverendbedford**
This gives you the new material models.  Plus we made a lot of changes to CMake to make things work on Windows.  We shall see how the MOOSE auto compile/testing handles that.

Closes #83

### CODE REVIEW

**Comment by reverendbedford** [comment]
Ugh, sigh.  Yes, "neml_export.h" can just be 

#ifndef NEML_EXPORT_H
#define NEML_EXPORT_H

#define NEML_EXPORT 
#define NEML_NO_EXPORT
#define NEML_DECPRECATED
#define NEML_DECPRECATED_EXPORT
#define NEML_DECPRECATED_NO_EXPORT

#endif 

(i.e. a bunch of null macros) for you but in the general case I need CMake to do the right thing and generate the correct Windows export magic words.  Uhh, suggestions?

**Comment by bwspenc** [comment]
So is neml_export.h generated by CMake?

**Comment by reverendbedford** [comment]
Yes

**Comment by dschwen** [comment]
When we get to MOOSE builds on Windows our config system will have to
generate the right values for those macros and we will just create a static
neml_exports.h that proxies our macros.

**Comment by bwspenc** [comment]
Hmm... that didn't work for some reason. I'll look into this after we get back from the break on Jan 2.

**Comment by bwspenc** [comment]
Taken care of by #111

**Pull request closed without merging**
