### PR TITLE
Regold an AD test

### PR DESCRIPTION
**Pull request by lindsayad**
We should always be computing the single point map during Jacobian computations. We should allow affine map computation during residual evaluation but right now our affine map tolerance is too loose in libmesh such that it introduces errors into the actual results. Consequently until we get our libMesh update in with a tightening of the affine map tolerance we should always compute the single point map. This is all discussed in [idaholab/moose#18714](https://github.com/idaholab/moose/pull/18714). This change means that previous gold results for slightly displaced meshes actually had errors in them. With the single point map computations, these results are more accurate, e.g. there are no errors due to assumptions about map affineness (that were actually wrong) and so these are definitely more "gold" than the previous golds.

Note that another round of re-golding will come once we update libmesh. That round will be updating non-AD tests at which time we will be able to again have the same gold file for both non-AD and AD

### CODE REVIEW

**Comment by bwspenc** [comment]
Looks good, merging

**Review by bwspenc — APPROVED** [review]

**Comment by bwspenc** [comment]
Accidentally merged before giving approval, but I did mean to approve this, so I did it right after the fact.

**Comment by lindsayad** [comment]
Thanks @bwspenc !

**Comment by lindsayad** [comment]
The change to always use a single point map (really, the change to not incorrectly detect an affine map) appears to lead to a heavily distorted element at the beginning of timestep 6 which creates a NaN in `ADComputeFiniteStraing::computeQpIncrements`. In debugging modes we catch this in an assertion and abort the simulation (hence why we changed the `method` that this test executes on). In optimized modes we chug on with a NaN in the residual...

As I've said on slack I'm wondering whether the ability to handle nan's within a line search is a new feature in PETSc. I say this because this is actually failing PETSc alt testing on MOOSE: https://civet.inl.gov/job/812711/. Since PETSc alt doesn't seem to have that feature, instead of being able to continue onto the next nonlinear iteration, it is registering the nonlinear solve as failed, and then MOOSE tries to cut the timestep. But this runs into `dtmin` for this problem.

The first thought I had was to just remove PETSc alt testing of Blackbear on MOOSE next branch testing, but the whole reason we have multiple PETSc versions tested is to catch brittle tests. I'm wondering whether there might be a way to make this test less brittle? It does indeed look like elements are becoming heavily distorted in this problem. It looks the original creator of this test is @recuero

**Comment by recuero** [comment]
I changed a couple of executioner settings, but I am really not sure that'd make a difference. I don't think I can activate PETSc alt testing for BlackBear (shouldn't we be able?)

**Comment by lindsayad** [comment]
Yea I don't think we have a recipe for that for blackbear itself (just for MOOSE testing). We should probably add it in the future. But for now I think we can test and see whether your changes had an impact on test robustness by trying add back `dbg` mode (see https://github.com/idaholab/blackbear/pull/253#issuecomment-912769907)

**Pull request merged**
