### PR TITLE
Remove deprecated param

### LINKED ISSUE #186: Remove deprecated legacy BC parameter
## Reason
The `use_legacy_dirichlet_bc` was deprecated and causes a warning to be emitted.

## Design
Remove it.

## Impact
No warning.

### PR DESCRIPTION
**Pull request by dschwen**
Close #186

### CODE REVIEW

**Comment by recuero** [comment]
Are we moving to `use_legacy_material_output = true`?

**Comment by dschwen** [comment]
No, the MOOSE default is now false and this parameter does not exist anymore.

**Comment by recuero** [comment]
From the most recent version of `MooseApp.C`:

```    params.addPrivateParam<const MooseMesh *>("_master_displaced_mesh");

  params.addParam<bool>(
      "use_legacy_material_output",
      true,
      "Set false to allow material properties to be output on INITIAL, not just TIMESTEP_END.");

  return params;

**Comment by dschwen** [comment]
D'Oh, I meant to only remove `use_legacy_dirichlet_bc`!

**Review by recuero — APPROVED** [review]
Looks good to me.

**Pull request merged**
