### PR TITLE
Add use_legacy_dirichlet_bc and use_legacy_material_output parameters

### LINKED ISSUE #177: Convergence issue of 2D-RZ_finiteStrain_resid.i from tensor mechanics
## Bug Description
blackbear-opt cause problem in converging some test from tensormechanics. 

## Steps to Reproduce
Addition of leagecy dirichlet BC and legacy material output in BlackBearApp.
## Impact
I could not to develop an axisymmetric model that runs well in BlackBear.

### PR DESCRIPTION
**Pull request by jain651**
This PR adds use_legacy_dirichlet_bc and use_legacy_material_output parameters in the BlackBearApp.C so that BlackBearApp runs the input file in the same way as TensorMechanics module. One example of such file is "moose/modules/tensor_mechanics/test/tests/2D_geometries/2D-RZ_finiteStrain_resid.i"

close #177

### CODE REVIEW

**Comment by jain651** [comment]
Close in favour of #176

**Comment by jain651** [comment]
Close and working on #176

**Comment by bwspenc** [comment]
So you want this one closed?  I can do that, but I think you should be able to close the PR.

**Comment by jain651** [comment]
I have closed this one.

**Pull request closed without merging**
