### PR TITLE
clang-format blackbear

### PR DESCRIPTION
**Pull request by bwspenc**
ref #33

### CODE REVIEW

**Comment by bwspenc** [comment]
@rwcarlsen, would you mind looking through this and making sure I've got everything (and merging it if it looks good)? It turns out that there were a fair number of files that were not clang-formatted, so the first commit does that. The second commit adds the hook and scripts that I pulled from MOOSE.

**Comment by rwcarlsen** [comment]
Looks fine.  Did you test if the merge-driver works?  To test it, you can create a feature branch that modifies some un-clangformatted code and then try to rebase that on-top of this branch.  You'll have to have run the install merge driver script and have the merge driver in your PATH for it to work.

**Comment by bwspenc** [comment]
No, I'll try that to see if it works.

**Comment by bwspenc** [comment]
@rwcarlsen I just checked, and nobody has any work in progress on blackbear, so I just removed those scripts since they really aren't necessary. I'll still need to sort that before doing this to the other apps where people have work in progress, but I think this PR is good to go.

**Comment by rwcarlsen** [comment]
We should get CIVET checks in before we merge this - otherwise you risk format regressions.

**Comment by bwspenc** [comment]
@brianmoose Can you turn the civet clang-format check on for blackbear commits?

**Comment by bwspenc** [comment]
@rwcarlsen This passes with the clang format check added to the civet recipe now.

**Comment by bwspenc** [comment]
FYI @agiorla.  You'll want to update your blackbear code before you start doing any new development.

**Comment by agiorla** [comment]
@bwspenc Will do! Thanks for letting me know.

**Pull request merged**
