### PR TITLE
Issue 115

### PR DESCRIPTION
**Pull request by lynnmunday**

### CODE REVIEW

**Comment by bwspenc** [comment]
This looks like it does a lot more than fix warnings (issue #115).  Did you unintentionally pick up other commits in this one?

**Comment by lynnmunday** [comment]
It does.  I forgot to go back to devel before I started this
I 'm trying to delete the pull request and fork

**Comment by bwspenc** [comment]
You don't have to delete the PR.  You can just `git rebase -i` to remove the ones you don't want and force push.

**Comment by lynnmunday** [comment]
I think I'm too late.  I already deleted the branch.  I'll try again

**Comment by dschwen** [comment]
I don't know how Ben handles it in Blackbear, but PR titles should not
contain the issue number, but a descriptive title on the moose repo.

**Comment by bwspenc** [comment]
Yes, I was going to say what @dschwen just said ^^^

**Pull request closed without merging**
