### PR TITLE
updating neml submodule, fixes chaboche hardening and string parsing interface

### PR DESCRIPTION
**Pull request by lynnmunday**
This neml update includes fixes for the chaboche hardening and modifies the string parsing interface to take a model name.
This is an improvement.
This is part of neml submodule maintenance
ref #66

### CODE REVIEW

**Comment by lynnmunday** [comment]
@bwspenc I was updating the neml submodule.  I wanted to see if I could.  My other pr needs the updated string parser interface that this has.

**Comment by bwspenc** [comment]
Yes, if the submodule update doesn't break anything (which it appears it does not), you can definitely do that.  Just one comment -- the message is kind of messy.  What does 'This is an improvement' mean? This kind of looks like it is the result of squashing several commits, but not editing the resulting combined message. This isn't a huge deal, but it matters because everything that is in there shows up in the commit history. This is the text I'm talking about:

This neml update includes fixes for the chaboche hardening and modifies the string parsing interface to take a model name.
This is an improvement.
This is part of neml submodule maintenance

**Comment by lynnmunday** [comment]
> Yes, if the submodule update doesn't break anything (which it appears it does not), you can definitely do that. Just one comment -- the message is kind of messy. What does 'This is an improvement' mean? This kind of looks like it is the result of squashing several commits, but not editing the resulting combined message. This isn't a huge deal, but it matters because everything that is in there shows up in the commit history. This is the text I'm talking about:
> 
> This neml update includes fixes for the chaboche hardening and modifies the string parsing interface to take a model name.
> This is an improvement.
> This is part of neml submodule maintenance

I edited the PR comment.  I thought only the git message showed up in the commit history but that is messy too.

**Comment by bwspenc** [comment]
Well, I actually already merged it. It's not a huge deal -- I brought that up mostly for future reference.

**Comment by bwspenc** [comment]
The revised version does look nice though!  I'm pretty sure it won't show up in the commit history since it was already merged.

**Pull request merged**
