### PR TITLE
Update NEML submodule

### PR DESCRIPTION
**Pull request by bwspenc**
ref #66

### CODE REVIEW

**Comment by bwspenc** [comment]
Thanks, @acasagran!
@lynnmunday This gives us that string parsing stuff now.

**Comment by lynnmunday** [comment]
@bwspenc I just updated my submodule and I don't get it.  When is it available

**Comment by bwspenc** [comment]
Did you `git pull --rebase upstream devel`, and then `git submodule update`?

**Comment by lynnmunday** [comment]
I did not rebase.  Now it does work.  I'll push my code changes with string parsing

**Pull request merged**
